plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "G:\\My Drive\\CocoCorp\\Coco Executioner\\Output\\2026-09-22 - Aisterra Tech Demo Site"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]